security:
    - '(exploit|exploits)'
enhancement:
    - '(improve|enhance|add|support|implement|fix|bug)'
performance:
    - '(speed|bench|benchmark|benchmarks|performance)'
interop:
    - '(marshal|native|natively|pointer|pointers)'
ci:
    - '(automatize|automate|automatically|automatic|build|deploy)'
gpu:
    - '(OpenGL|Vulkan|DirectX|GL|Vk|Dx|ULGPUDriver|GPUDriver|shader|shaders|mesh|pipeline|gpu|rt|vertex|vertices|triangle|triangles|polygon|polygons|depth|blend)'
