security:
    - '(exploit|exploits)'
enhancement:
    - '(improve|enhance|add|support)'
performance:
    - '(speed|bench|benchmark|benchmarks|performance)'
interop:
    - '(marshal|native|natively|pointer|pointers)'
ci:
    - '(automatize|automate|automatically|automatic|build|deploy)'
