name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: pack Binaries
        run: |
          dotnet pack -c Release UltralightNet.Binaries/UltralightNet.Binaries.csproj
      #- name: Install dependencies
      #  run: dotnet restore -f UltralightSharp/UltralightSharp.csproj
      - name: Build
        run: dotnet build -c Release --project UltralightNet/UltralightNet.csproj

      - name: Test
        run: dotnet test --project UltralightNet.Test/UltralightNet.Test.csproj
