name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack
        run: |
          dotnet pack UltralightNet.Binaries
          dotnet pack UltralightNet
          dotnet pack UltralightNet.AppCore
          dotnet pack UltralightNet.Resources
      - run: sudo apt install  libpng12-0
        if: matrix.os=='windows-latest'
      - name: Test Application
        run: dotnet run --project UltralightNet.TestApplication
      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj --verbosity normal
