name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack
        run: |
          dotnet pack UltralightNet.Binaries
          dotnet pack UltralightNet
          dotnet pack UltralightNet.AppCore
          dotnet pack UltralightNet.Resources
      - run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
          echo sudo dpkg -i libpng12-0_1.2.54-1ubuntu1.1_amd64.deb
          sudo add-apt-repository ppa:linuxuprising/libpng12
          sudo apt update
          sudo apt install libpng12-0
        if: matrix.os=='ubuntu-latest'
      - name: Test Application
        run: dotnet run --project UltralightNet.TestApplication
      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj --verbosity normal
