name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build Core
        run: |
          dotnet build -c Release UltralightSharp.Core/UltralightSharp.Core.csproj
      #- name: Install dependencies
      #  run: dotnet restore -f UltralightSharp/UltralightSharp.csproj
      - name: Build
        run: dotnet build -c Release
      #- name: Publish Build
      #  run: dotnet publish -c Release
      - name: Run Demo
        run: dotnet run -c Release --project UltralightSharp.SafeDemo/UltralightSharp.SafeDemo.csproj
      - uses: actions/upload-artifact@v2
        with:
          name: NuGet Package(s) built by ${{ matrix.os }}
          path: '**/*.nupkg'
          if-no-files-found: error
