name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            '*/bin/'
            '*/obj/'
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - name: Pack UltralightNet.Binaries
        run: dotnet pack -c Release UltralightNet.Binaries/UltralightNet.Binaries.csproj
      - name: Build UltralightNet
        run: dotnet build -c Release UltralightNet/UltralightNet.csproj
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            '*/bin/'
            '*/obj/'
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}
      - name: Pack UltralightNet.Binaries
        run: dotnet pack -c Release UltralightNet.Binaries/UltralightNet.Binaries.csproj
      - name: Build UltralightNet
        run: dotnet build -c Release UltralightNet/UltralightNet.csproj

      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj
