name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: pack Binaries
        run: dotnet pack -c Release UltralightNet.Binaries/UltralightNet.Binaries.csproj
      - name: Build
        run: dotnet build -c Release UltralightNet/UltralightNet.csproj
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack Binaries
        run: dotnet pack -c Release UltralightNet.Binaries/UltralightNet.Binaries.csproj
      - name: Build UltralightNet
        run: dotnet build -c Release UltralightNet/UltralightNet.csproj

      - name: Test
        continue-on-error: true
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - run: tree
