name: Test & Deploy
on:
  push:
    branches: [ 'master' ]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Pack
        run: |
          dotnet pack UltralightNet.Binaries
          dotnet pack UltralightNet
          dotnet pack UltralightNet.AppCore
          dotnet pack UltralightNet.Resources
      - run: | # missing libraries workaround
          sudo add-apt-repository ppa:linuxuprising/libpng12
          sudo apt update
          sudo apt install libpng12-0
          find /usr/lib -name "libffi.so*"
          sudo ln -s  /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0  /usr/lib/x86_64-linux-gnu/libffi.so.6
        if: matrix.os=='ubuntu-latest'
      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Pack
      run: |
        dotnet pack -c Release UltralightNet.Binaries
        dotnet pack -c Release UltralightNet
        dotnet pack -c Release UltralightNet.AppCore
        dotnet pack -c Release UltralightNet.Resources
    - run: tree
    - name: Publish
      run: |
        dotnet nuget push UltralightNet.Binaries.*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push UltralightNet.*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push UltralightNet.AppCore.*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push UltralightNet.Resources.*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
      continue-on-error: true
