name: Test & Deploy
on:
  push:
    branches: [ 'master' ]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack
        run: |
          dotnet pack UltralightNet.Binaries
          dotnet pack UltralightNet
          dotnet pack UltralightNet.AppCore
          dotnet pack UltralightNet.Resources
      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj --verbosity normal
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Pack
      run: |
        dotnet pack UltralightNet.Binaries
        dotnet pack UltralightNet
        dotnet pack UltralightNet.AppCore
        dotnet pack UltralightNet.Resources
    - run: tree
    - name: Publish
      run: dotnet nuget push UltralightNet.*.nupkg -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
